# ==== some info ====
# Search by substring : C+F (and esc/C-c for exit)

[window]
decorations = "none"
padding = { x = 10, y = 10 }

[scrolling]
history=100000

[keyboard]
bindings = [
  { key = "Back", mods = "Control", chars = "\u0017" },
  { key = "Delete", mods = "Control", chars = "\u001bd" },

  # check https://github.com/alacritty/alacritty/issues/5450
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
]
