#!/usr/bin/env bash

{
    tmux list-sessions -F '#S' | grep -v '^_popup_' | while read -r session; do
        echo "SESSION: $session"

        tmux list-windows -t "$session" -F 'WINDOW: #S:#I #W'

        tmux list-windows -t "$session" -F '#I' | while read -r window; do
            tmux list-panes -t "$session:$window" -F "PANE: #S:#I.#P  #{pane_current_command}"
        done
    done
} | sed 's/^SESSION:/S /' | sed 's/^WINDOW:/  W /' | sed 's/^PANE:/    P /' |
    fzf --reverse |
    awk '{
        if ($1 == "S") {
            print $2
        } else if ($1 == "W") {
            print $2
        } else if ($1 == "P") {
            print $2
        }
    }' |
    xargs tmux switch-client -t
