#!/usr/bin/env bash

{
    tmux list-sessions -F '#S' | grep -v '^_popup_' | while read -r session; do
        echo "S $session"

        tmux list-windows -t "$session" -F '#I #W' | while read -r window_id window_name; do
            echo "W $session:$window_id"

            tmux list-panes -t "$session:$window_id" -F "P $session:$window_id.#P"
        done
    done
} | fzf --reverse |
    awk '{
        if ($1 == "S") {
            print $2
        } else if ($1 == "W") {
            print $2
        } else if ($1 == "P") {
            print $2
        }
    }' |
    xargs tmux switch-client -t
