#!/usr/bin/env bash

MAX_VOLTAGE=16800
MIN_VOLTAGE=12000

VOLTAGE=$(cat /sys/class/power_supply/BAT0/voltage_now)
VOLTAGE_MV=$((VOLTAGE / 1000))

PERCENT=$(echo "scale=0; ($VOLTAGE_MV - $MIN_VOLTAGE) * 100 / ($MAX_VOLTAGE - $MIN_VOLTAGE)" | bc)

[ $PERCENT -gt 100 ] && PERCENT=100
[ $PERCENT -lt 0 ] && PERCENT=0

echo "BAT ${PERCENT}% (${VOLTAGE_MV}mV)"
