#!/usr/bin/env bash

# stolen from https://github.com/vivien/i3blocks-contrib/blob/master/wifi/wifi

IF="wlo1"

if [[ ! -d /sys/class/net/${IF}/wireless ]]; then
    echo '{"full_text":"no wifi","color":"#FF0000"}'
    exit
fi

if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
    echo '{"full_text":"wifi down","color":"#FF0000"}'
    exit
fi

Q=$(iw dev $IF link | grep 'dBm$' | grep -Eoe '-[0-9]{2}' | awk '{print ($1 > -50 ? 100 : ($1 < -100 ? 0 : ($1+100)*2))}')

if [ -z "$Q" ]; then
    echo '{"full_text":"no wifi signal","color":"#FF0000"}'
    exit
fi

if [ $Q -ge 80 ]; then
    C="#00FF00"
elif [ $Q -ge 60 ]; then
    C="#FFF600"
elif [ $Q -ge 40 ]; then
    C="#FFAE00"
else
    C="#FF0000"
fi

echo '{"full_text":"wifi '"$Q"'%","color":"'"$C"'"}'
